# Generated by Django 6.0.7 on 2026-07-11 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=88, verbose_name='可用积分')),
                ('frozen_balance', models.IntegerField(default=0, verbose_name='冻结积分')),
                ('total_consumed', models.IntegerField(default=0, verbose_name='累计消费')),
                ('total_redeemed', models.IntegerField(default=0, verbose_name='累计兑换')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '积分账户',
                'verbose_name_plural': '积分账户',
            },
        ),
        migrations.CreateModel(
            name='RedemptionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='兑换码')),
                ('points', models.PositiveIntegerField(verbose_name='兑换积分')),
                ('status', models.CharField(choices=[('unused', '未使用'), ('used', '已使用'), ('expired', '已过期'), ('disabled', '已禁用')], default='unused', max_length=16, verbose_name='状态')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('batch_name', models.CharField(blank=True, max_length=64, verbose_name='批次')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_codes', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '兑换码',
                'verbose_name_plural': '兑换码',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('redeem', '兑换'), ('freeze', '冻结'), ('consume', '消费'), ('refund', '退款'), ('admin_adjust', '管理员调整')], max_length=32, verbose_name='动作')),
                ('amount', models.IntegerField(verbose_name='积分变化')),
                ('balance_after', models.IntegerField(verbose_name='可用积分快照')),
                ('frozen_after', models.IntegerField(verbose_name='冻结积分快照')),
                ('reason', models.CharField(max_length=64, verbose_name='原因')),
                ('idempotency_key', models.CharField(max_length=160, verbose_name='幂等 Key')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('external_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_ledgers', to='creator.externaljob')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_ledgers', to='creator.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_ledgers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '积分流水',
                'verbose_name_plural': '积分流水',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'action', 'idempotency_key'), name='uniq_point_action_key')],
            },
        ),
    ]
