# Generated by Django 6.0.7 on 2026-07-11 08:51

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=apps.accounts.models.generate_uid, max_length=16, unique=True, verbose_name='UID')),
                ('wx_openid', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='微信 OpenID')),
                ('wx_unionid', models.CharField(blank=True, max_length=128, verbose_name='微信 UnionID')),
                ('nickname', models.CharField(blank=True, max_length=64, verbose_name='昵称')),
                ('avatar_url', models.URLField(blank=True, verbose_name='头像')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='手机号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
    ]
