# Generated by Django 6.0.7 on 2026-07-14 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accesstoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRightsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('complaint', '投诉举报'), ('account_delete', '注销账号'), ('data_export', '导出个人数据'), ('data_delete', '删除个人数据')], max_length=32, verbose_name='申请类型')),
                ('content', models.TextField(blank=True, verbose_name='申请说明')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('completed', '已完成'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='状态')),
                ('response_note', models.TextField(blank=True, verbose_name='处理说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rights_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户权益申请',
                'verbose_name_plural': '用户权益申请',
                'ordering': ['-created_at'],
            },
        ),
    ]
