# Generated by Django 6.0.7 on 2026-07-11 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('source_audio', '克隆源音频'), ('tts_audio', '配音音频'), ('source_video', '源视频'), ('output_video', '成片视频')], max_length=32, verbose_name='文件类型')),
                ('storage_type', models.CharField(choices=[('local', '本地'), ('server_public', '服务器公网'), ('oss', '阿里云 OSS'), ('cos', '腾讯云 COS'), ('remote', '第三方远程 URL')], default='local', max_length=32, verbose_name='存储类型')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='文件路径')),
                ('file_url', models.URLField(blank=True, max_length=800, verbose_name='文件 URL')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='文件大小')),
                ('duration', models.FloatField(default=0, verbose_name='时长秒')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME')),
                ('checksum', models.CharField(blank=True, max_length=128, verbose_name='校验值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '媒体文件',
                'verbose_name_plural': '媒体文件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='标题')),
                ('source_type', models.CharField(default='manual', max_length=32, verbose_name='来源类型')),
                ('source_url', models.URLField(blank=True, max_length=800, verbose_name='来源链接')),
                ('original_text', models.TextField(blank=True, verbose_name='原文')),
                ('rewritten_text', models.TextField(blank=True, verbose_name='改写文案')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('rewriting', '改写中'), ('rewrite_done', '改写完成'), ('tts_done', '配音完成'), ('video_uploaded', '视频已上传'), ('generating', '生成中'), ('completed', '已完成'), ('failed', '失败')], default='draft', max_length=32, verbose_name='状态')),
                ('current_step', models.CharField(choices=[('script', '文案'), ('rewrite', '改写'), ('tts', '配音'), ('video', '视频'), ('generating', '生成中'), ('preview', '预览')], default='script', max_length=32, verbose_name='当前步骤')),
                ('point_cost_total', models.IntegerField(default=0, verbose_name='累计消耗积分')),
                ('refund_status', models.CharField(blank=True, max_length=32, verbose_name='退款状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('output_video_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_video_tasks', to='creator.mediafile')),
                ('source_video_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_video_tasks', to='creator.mediafile')),
                ('tts_audio_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tts_tasks', to='creator.mediafile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '创作任务',
                'verbose_name_plural': '创作任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mediafile',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='creator.task'),
        ),
        migrations.CreateModel(
            name='ExternalJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64, verbose_name='供应商')),
                ('job_type', models.CharField(max_length=64, verbose_name='任务类型')),
                ('provider_task_id', models.CharField(blank=True, max_length=160, verbose_name='供应商任务 ID')),
                ('status', models.CharField(choices=[('pending', '待提交'), ('submitted', '已提交'), ('processing', '处理中'), ('succeeded', '成功'), ('failed', '失败')], default='pending', max_length=32, verbose_name='状态')),
                ('request_payload_summary', models.JSONField(blank=True, default=dict, verbose_name='请求摘要')),
                ('response_payload_summary', models.JSONField(blank=True, default=dict, verbose_name='响应摘要')),
                ('result_url', models.URLField(blank=True, max_length=800, verbose_name='结果 URL')),
                ('cost_points', models.IntegerField(default=0, verbose_name='积分成本')),
                ('error_code', models.CharField(blank=True, max_length=80, verbose_name='错误码')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_jobs', to=settings.AUTH_USER_MODEL)),
                ('result_media_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_result_jobs', to='creator.mediafile')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_jobs', to='creator.task')),
            ],
            options={
                'verbose_name': '外部任务',
                'verbose_name_plural': '外部任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64, verbose_name='供应商')),
                ('api_type', models.CharField(max_length=64, verbose_name='接口类型')),
                ('endpoint', models.CharField(blank=True, max_length=300, verbose_name='接口地址')),
                ('http_status', models.IntegerField(default=0, verbose_name='HTTP 状态')),
                ('request_status', models.CharField(default='success', max_length=32, verbose_name='请求状态')),
                ('request_id', models.CharField(blank=True, max_length=160, verbose_name='请求 ID')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='耗时 ms')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_call_logs', to=settings.AUTH_USER_MODEL)),
                ('external_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_call_logs', to='creator.externaljob')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_call_logs', to='creator.task')),
            ],
            options={
                'verbose_name': '接口调用日志',
                'verbose_name_plural': '接口调用日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='音色名称')),
                ('provider', models.CharField(default='coze_minimax', max_length=64, verbose_name='供应商')),
                ('provider_voice_id', models.CharField(blank=True, max_length=128, verbose_name='供应商 voice_id')),
                ('sample_audio_url', models.URLField(blank=True, max_length=800, verbose_name='试听音频 URL')),
                ('clone_test_text', models.CharField(blank=True, max_length=220, verbose_name='试听文案')),
                ('status', models.CharField(choices=[('cloning', '克隆中'), ('pending_confirm', '待确认'), ('available', '可用'), ('failed', '失败'), ('expired', '已过期'), ('discarded', '已丢弃')], default='pending_confirm', max_length=32, verbose_name='状态')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认入库时间')),
                ('first_used_at', models.DateTimeField(blank=True, null=True, verbose_name='首次使用时间')),
                ('must_use_before', models.DateTimeField(blank=True, null=True, verbose_name='必须使用截止')),
                ('discarded_at', models.DateTimeField(blank=True, null=True, verbose_name='丢弃时间')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sample_audio_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_voice_set', to='creator.mediafile')),
                ('source_audio_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_voice_set', to='creator.mediafile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '音色',
                'verbose_name_plural': '音色',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='selected_voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='creator.voice'),
        ),
    ]
