# Generated by Django 6.0.7 on 2026-07-13 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_alter_mediafile_storage_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='externaljob',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=160, verbose_name='提交幂等 Key'),
        ),
        migrations.AddField(
            model_name='voice',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=160, verbose_name='克隆幂等 Key'),
        ),
        migrations.AddConstraint(
            model_name='externaljob',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('user', 'provider', 'job_type', 'idempotency_key'), name='uniq_external_job_key'),
        ),
        migrations.AddConstraint(
            model_name='voice',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('user', 'idempotency_key'), name='uniq_voice_clone_key'),
        ),
    ]
