# Generated by Django 6.0.7 on 2026-07-14 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0003_externaljob_idempotency_key_voice_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_confirmed', models.BooleanField(default=False, verbose_name='确认本人声音或已获授权')),
                ('separate_consent_confirmed', models.BooleanField(default=False, verbose_name='确认已取得被编辑者单独同意')),
                ('statement_version', models.CharField(default='voice-auth-v1', max_length=32, verbose_name='授权声明版本')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='客户端')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, verbose_name='同意时间')),
                ('source_audio_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_authorizations', to='creator.mediafile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_authorizations', to=settings.AUTH_USER_MODEL)),
                ('voice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization', to='creator.voice')),
            ],
            options={
                'verbose_name': '声音克隆授权',
                'verbose_name_plural': '声音克隆授权',
                'ordering': ['-accepted_at'],
            },
        ),
    ]
